/**
 * brain-adapter — reads pi-brain's .memory/ directory and surfaces structured data.
 *
 * pi-brain owns storage (Git-backed commits, branches, state). This module is the
 * read-only bridge that translates pi-brain file formats into types zosma-memory
 * can work with. It never writes to pi-brain files.
 *
 * Supported pi-brain layout:
 *   .memory/
 *     state.yaml                      — active branch, last commit, sessions
 *     branches/<name>/commits.md      — distilled milestone snapshots
 *     branches/<name>/metadata.yaml   — branch metadata
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs"
import { join } from "node:path"
import remarkParse from "remark-parse"
import { unified } from "unified"
import { parse as parseYaml } from "yaml"

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface BrainState {
	activeBranch: string
	initialized: boolean
	lastCommit: {
		branch: string
		hash: string
		timestamp: string
		summary: string
	} | null
}

export interface ParsedCommit {
	/** 8-char hex hash generated by pi-brain */
	hash: string
	/** ISO timestamp string */
	timestamp: string
	/** Full markdown content of the commit block */
	content: string
	/** Branch this commit belongs to */
	branch: string
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

/**
 * Read and parse .memory/state.yaml.
 * Returns a safe default when the file is absent or unparseable.
 */
export const readState = (memoryDir: string): BrainState => {
	const statePath = join(memoryDir, "state.yaml")
	if (!existsSync(statePath)) {
		return { activeBranch: "main", initialized: false, lastCommit: null }
	}

	try {
		const raw = readFileSync(statePath, "utf-8")
		const data = parseYaml(raw) as Record<string, unknown>

		let lastCommit: BrainState["lastCommit"] = null
		if (data.last_commit && typeof data.last_commit === "object" && !Array.isArray(data.last_commit)) {
			const lc = data.last_commit as Record<string, unknown>
			lastCommit = {
				branch: String(lc.branch ?? ""),
				hash: String(lc.hash ?? ""),
				timestamp: String(lc.timestamp ?? ""),
				summary: String(lc.summary ?? ""),
			}
		}

		return {
			activeBranch: typeof data.active_branch === "string" ? data.active_branch : "main",
			initialized: typeof data.initialized === "string" && data.initialized !== "",
			lastCommit,
		}
	} catch {
		return { activeBranch: "main", initialized: false, lastCommit: null }
	}
}

// ---------------------------------------------------------------------------
// Branches
// ---------------------------------------------------------------------------

/**
 * List all branch names in .memory/branches/.
 */
export const listBranches = (memoryDir: string): string[] => {
	const branchesDir = join(memoryDir, "branches")
	if (!existsSync(branchesDir)) return []
	return readdirSync(branchesDir).filter((entry) => statSync(join(branchesDir, entry)).isDirectory())
}

/**
 * Read raw commits.md content for a branch. Returns empty string when absent.
 */
export const readCommitsRaw = (memoryDir: string, branch: string): string => {
	const p = join(memoryDir, "branches", branch, "commits.md")
	if (!existsSync(p)) return ""
	return readFileSync(p, "utf-8")
}

// ---------------------------------------------------------------------------
// Commit parsing (remark AST, not regex)
// ---------------------------------------------------------------------------

const processor = unified().use(remarkParse)

/**
 * Parse raw commits.md text into structured ParsedCommit objects.
 *
 * pi-brain writes commits in the format:
 *   ## Commit <hash> | <ISO-timestamp>
 *   [content until next --- separator]
 *
 * We use remark to parse the document into an AST, then walk headings to
 * locate commit blocks rather than relying on raw string patterns.
 */
export const parseCommits = (raw: string, branch: string): ParsedCommit[] => {
	if (!raw.trim()) return []

	const tree = processor.parse(raw)
	const commits: ParsedCommit[] = []

	let currentHash: string | null = null
	let currentTimestamp: string | null = null
	const contentLines: string[] = []

	const flushCurrent = (): void => {
		if (currentHash && currentTimestamp) {
			commits.push({
				hash: currentHash,
				timestamp: currentTimestamp,
				content: contentLines.join("\n").trim(),
				branch,
			})
		}
		contentLines.length = 0
	}

	for (const node of tree.children) {
		if (node.type === "heading" && node.depth === 2) {
			const text = node.children.map((c) => ("value" in c ? String((c as { value: unknown }).value) : "")).join("")

			// Match: "Commit abc12345 | 2026-04-01T12:00:00.000Z"
			const m = text.match(/^Commit\s+([0-9a-f]{8})\s*\|\s*(.+)$/)
			if (m) {
				flushCurrent()
				currentHash = m[1]
				currentTimestamp = m[2].trim()
				continue
			}
		}

		// Skip thematic breaks (---) that pi-brain uses as separators
		if (node.type === "thematicBreak") {
			continue
		}

		// Accumulate content for the current commit
		if (currentHash && node.position) {
			// Slice the original raw text using node positions for fidelity
			const start = node.position.start.offset ?? 0
			const end = node.position.end.offset ?? 0
			contentLines.push(raw.slice(start, end))
		} else if (currentHash && node.type === "paragraph") {
			const text = node.children.map((c) => ("value" in c ? String((c as { value: unknown }).value) : "")).join("")
			contentLines.push(text)
		}
	}

	flushCurrent()
	return commits
}
